name: "lila-tictactoe"

database:
  address:
    - "postgres://postgres:eFGggNMsbGdDZzlzZMNNQtSfbSprCdql@postgres.railway.internal:5432/railway"

runtime:
  js_entrypoint: "build/index.js"
  http_key: "defaultkey"

socket:
  server_key: "defaultkey"
  port: 7352

  cors_allow_origins:
    - "*"

session:
  encryption_key: "encryptionkey123"
  refresh_encryption_key: "refreshkey456"
  token_expiry_sec: 7200

console:
  port: 7351
  address: "0.0.0.0"